### ISSUE TITLE
docker-compose file for MongoDB

### ISSUE THREAD

**Issue by mwllgr** [Typhonragewind/meshcentral-docker#2]
I think it would be a good idea to add a compose file with MongoDB for reference.
Here's mine - everything works:

```
version: '3'
services:
    mongodb:
        container_name: meshcentral_db
        restart: always
        image: mongo:latest
        expose:
            - 27017
        volumes:
            - '/opt/meshcentral/database:/data/db'
    meshcentral:
        restart: always
        container_name: meshcentral
        depends_on:
            - 'mongodb'
        image: typhonragewind/meshcentral
        ports:
            - 127.0.0.1:8086:4430
            - 127.0.0.1:8087:800
        environment:
            - HOSTNAME=xxxxx
            - REVERSE_PROXY=xxxxxx
            - REVERSE_PROXY_TLS_PORT=443
            - IFRAME=true
            - ALLOW_NEW_ACCOUNTS=false
            - WEBRTC=false
            - NODE_ENV=production
        volumes:
            - ./meshcentral/data:/opt/meshcentral/meshcentral-data
            - ./meshcentral/user_files:/opt/meshcentral/meshcentral-files
```

... and in `meshcentral/data/config.json`:

```
{
   // ...
   "settings":{
      // ...
      "mongodb": "mongodb://mongodb:27017/mesh",
      "mongodbcol": "mesh",
      // ...
   }
   // ...
}
```
