### ISSUE TITLE
Getting error in browser ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by diogo24m** [Typhonragewind/meshcentral-docker#51]
I'm getting an error in browser ERR_TOO_MANY_REDIRECTS using coolify's proxy (traefik)

I have changed docker-compose.yml to this:
```
version: '3'
services:
  meshcentral:
    container_name: meshcentral
    image: 'typhonragewind/meshcentral:latest'
    environment:
      - HOSTNAME=my.domain.com
      - REVERSE_PROXY=xxx.xx.xx.xx
      - REVERSE_PROXY_TLS_PORT=443
      - IFRAME=false
      - ALLOW_NEW_ACCOUNTS=true
      - WEBRTC=false
      - BACKUPS_PW=MyAwesomePasswordPleaseChangeMe
      - BACKUP_INTERVAL=24
      - BACKUP_KEEP_DAYS=7
    volumes:
      - './meshcentral/data:/opt/meshcentral/meshcentral-data'
      - './meshcentral/user_files:/opt/meshcentral/meshcentral-files'
      - './meshcentral/backups:/opt/meshcentral/meshcentral-backups'
```

In the logs show this:
```
MeshCentral HTTPS server running on my.domain.com:443.
Loaded web certificate from "https://xxx.xx.xx.xx:443", host: "my.domain.com"
  SHA384 cert hash: d109f2fd321973194fd3d6217bb12e4f1b0ef2c0451187b623401b825f07b512d83d91ba425bbfca94aab5d5b3832a01
  SHA384 key hash: 1f440cf88e68e2d5fc83b9eadcef3f72e7da061a62d4fe4d4632512774dfccfbd1b8ad1238e04335e21c951775b790d0
```

With cloudflare dns configured like this:
A | my.domain.com | xxx.xx.xx.xx | DNS only

I also forced cloudflare to use SSL to connect to this domain
